### ISSUE TITLE
Commands via DM breaks

### ISSUE THREAD

**Issue by reaganiwadha** [alex-taxiera/eris-boiler#66]
Returning something in a CommandAction breaks if the command was sent via a DM

```
06/24 21:07:58 | error processing command response: TypeError: channel.permissionsOf is not a function
    at Orator.createMessage (/home/a/Projects/apollo-bot/node_modules/eris-boiler/lib/orator/index.js:72:33)
    at Orator._processCommandResponse (/home/a/Projects/apollo-bot/node_modules/eris-boiler/lib/orator/index.js:321:18)
    at /home/a/Projects/apollo-bot/node_modules/eris-boiler/lib/orator/index.js:128:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by alex-taxiera** [comment]
fixed by #67
